apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
 # - image: gcr.io/k8s-skaffold/skaffold-example
  - image: quickstart-se

deploy:
  kubectl:
    manifests:
    #  - k8s-*
      - target/app.yaml
